# Generated by Django 5.2.6 on 2025-10-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GraphicDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="graphics/")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("branding", "Branding & Identity"),
                            ("ui-ux", "UI/UX Design"),
                            ("print", "Print Design"),
                            ("digital", "Digital Art"),
                            ("fullstack", "Full Stack Project"),
                        ],
                        default="branding",
                        max_length=100,
                    ),
                ),
                ("tools_used", models.CharField(max_length=200)),
                ("client", models.CharField(blank=True, max_length=200)),
                ("project_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_featured", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SoftwareProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="software/")),
                ("technologies", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("web", "Web Application"),
                            ("mobile", "Mobile App"),
                            ("api", "API Development"),
                            ("desktop", "Desktop Software"),
                            ("fullstack", "Full Stack Project"),
                        ],
                        default="web",
                        max_length=100,
                    ),
                ),
                ("project_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("completion_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_featured", models.BooleanField(default=False)),
            ],
        ),
    ]
